version: "3.9"

services:

  opencr-fhir:
    image: "hapiproject/hapi:v5.1.0"
    restart: unless-stopped
    environment:
     - CR_DATABASE_URL=${CR_DATABASE_URL}
     - CR_DATABASE_USERNAME=${CR_DATABASE_USERNAME}
     - CR_DATABASE_PW=${CR_DATABASE_PW}
     #the line below breaks when activated
     #- JAVA_OPTS='-Dspring.datasource.url=${CR_DATABASE_URL} -Dspring.datasource.username=${CR_DATABASE_USERNAME} -Dspring.datasource.password=${CR_DATABASE_PW} -Dspring.datasource.driverClassName=org.postgresql.Driver'
  
    volumes:
      - opencr-data-new:/data/hapi
    networks:
      - opencr
      - default
     

volumes:
  opencr-data-new:

networks:
  default:
  opencr:
    name: opencr
    external: true




  