services:
  mongo-1:
    command: ["--replSet", "mongo-set", "--wiredTigerCacheSizeGB", "0.5"]
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MONGO_1_PLACEMENT}"

  mongo-2:
    image: ${MONGO_IMAGE}
    volumes:
      - "openhim-mongo-02:/data/db"
      - "openhim-mongo-02-config:/data/configdb"
    command: ["--replSet", "mongo-set", "--wiredTigerCacheSizeGB", "0.5"]
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MONGO_2_PLACEMENT}"
      replicas: 1
      resources:
        limits:
          cpus: ${MONGO_CPU_LIMIT}
          memory: ${MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${MONGO_CPU_RESERVE}
          memory: ${MONGO_MEMORY_RESERVE}
    networks:
      default:
      xds-repo-mongo:
      mongo_backup_net:

  mongo-3:
    image: ${MONGO_IMAGE}
    volumes:
      - "openhim-mongo-03:/data/db"
      - "openhim-mongo-03-config:/data/configdb"
    command: ["--replSet", "mongo-set", "--wiredTigerCacheSizeGB", "0.5"]
    deploy:
      placement:
        constraints:
          - "node.labels.name==${MONGO_3_PLACEMENT}"
      replicas: 1
      resources:
        limits:
          cpus: ${MONGO_CPU_LIMIT}
          memory: ${MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${MONGO_CPU_RESERVE}
          memory: ${MONGO_MEMORY_RESERVE}
    networks:
      default:
      xds-repo-mongo:
      mongo_backup_net:

volumes:
  openhim-mongo-02:
  openhim-mongo-03:
  openhim-mongo-02-config:
  openhim-mongo-03-config: