projectName: isanteplus-local
image: itechuw/isanteplus-local:latest
logPath: /tmp/logs

packages:
  - interoperability-layer-openhim
  - reverse-proxy-nginx
  - database-mysql
  - identity-access-manager-keycloak
  - emr-isanteplus
  - data-pipeline-isanteplus

