version: '2.4'

## Port Assignments:
##  See .env file

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

## Utility for booting up placeholder page:
# `docker run --hostname openhim-placeholder --network shared-health-record_sedish --name openhim-placeholder -e MESSAGE=OPENHIM-PLACEHOLDER -e PORT=3000 -d docker.io/sroze/landing-page:latest`

services:
  ###
  # NGINX
  ###

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    networks: 
      - sedish
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/isanteplus-pilot.org:/etc/letsencrypt
      - ./docker/nginx/data/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/nginx/.htpasswd:/etc/nginx/.htpasswd

  ###
  # OpenCR
  ###
  opencr:
    container_name: opencr
    hostname: opencr
    build: ./docker/opencr
    restart: on-failure
    environment:
      - NODE_ENV=docker
    networks:
      - sedish
    volumes:
      - ./config/opencr/mediator.json:/src/server/config/mediator.json
      - ./config/opencr/config_docker_template.json:/src/server/config/config_docker.json
      - ./config/opencr/decisionRules.json:/src/server/config/decisionRules.json
  opencr-fhir:
    image: "hapiproject/hapi:v5.0.0"
    container_name: opencr-fhir
    restart: unless-stopped
    networks:
      - sedish
    volumes:
      - cr-data:/data/hapi
      - ./config/opencr/hapi.properties:/conf/hapi/hapi.properties
    environment:
      JAVA_OPTS: '-Dhapi.properties=/conf/hapi/hapi.properties'
  opencr-es:
    container_name: opencr-es
    hostname: opencr-es
    image: intrahealth/elasticsearch:latest
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - sedish

  ###
  # SHR
  ###
  shr:
    container_name: shr
    hostname: shr
    build:
      context: shr
    restart: on-failure
    environment:
      - NODE_ENV=docker
    networks:
      - sedish
    volumes:
      - ./config/shr/mediator_docker.json:/src/server/config/mediator_docker.json
      - ./config/shr/config_docker_template.json:/src/server/config/config_docker_template.json


  shr-fhir:
    image: "hapiproject/hapi:v5.0.0"
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    volumes:
      - shr-data:/data/hapi
      - ./config/shr/hapi.properties:/conf/hapi/hapi.properties
    environment:
      JAVA_OPTS: '-Dhapi.properties=/conf/hapi/hapi.properties' 
    networks:
      - sedish

  ###
  # iSantePlus
  ###
  isanteplus:
    container_name: isanteplus
    hostname: isanteplus
    build: ./docker/openmrs-server
    restart: unless-stopped
    env_file:
        - ./openmrs/isanteplus/openmrs-server.env
    volumes:
      - ./openmrs/isanteplus/distribution:/openmrs/distribution
      - openmrs-data:/openmrs/data
    networks:
      - sedish
    ports:
      - 8000:8000

  isanteplus-two:
    container_name: isanteplus-two
    hostname: isanteplus-two
    build: ./docker/openmrs-server
    restart: unless-stopped
    env_file:
        - ./openmrs/isanteplus/openmrs-server-fsc.env
    volumes:
      - ./openmrs/isanteplus/distribution-fsc:/openmrs/distribution
      - openmrs-data2:/openmrs/data
    networks:
      - sedish
    ports:
        - 8001:8001
  ###
  # OpenHIM
  ###
  openhim-core:
    container_name: openhim-core
    hostname: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: mongodb://mongo:27017/openhim
      mongo_atnaUrl: mongodb://mongo:27017/openhim
      NODE_ENV: "production"
    ports:
      - 8080:8080
      - 5000:5000
      - 5001:5001
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - sedish
    volumes:
      - ./config/openhim-core/production.json:/usr/src/app/config/production.json
      - /etc/letsencrypt/archive/isanteplus-pilot.org:/etc/letsencrypt/isanteplus-pilot.org

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    volumes:
      - ./config/openhim-console/default.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - sedish

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
    networks:
      - sedish
    restart: unless-stopped

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  openmrs-data:
    driver: local
  openmrs-data2:
    driver: local
  mongo-data:
    driver: local
  shr:
    driver: local
  cr-data:
    driver: local
  shr-data:
    driver: local
  data011:
    driver: local
  data012:
    driver: local
  es-data:
    driver: local    
  hapi-data:
    driver: local
networks:
  sedish:
