version: '2.4'

## Port Assignments:
##  See .env file

## Container debugging: 
# 1. append the following lines to desired container 
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
# 
#    tty: true
#    stdin_open: true
#    entrypoint: bash

## Utility for booting up placeholder page:
# `docker run --hostname openhim-placeholder --network shared-health-record_sedish --name openhim-placeholder -e MESSAGE=OPENHIM-PLACEHOLDER -e PORT=3000 -d docker.io/sroze/landing-page:latest`

services:
  ###
  # NGINX
  ###

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/letsencrypt
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx-data:/var/www
      - /home/ubuntu/nginx/.htpasswd:/etc/nginx/.htpasswd

    networks:
      - sedish

  certbot:
    image: certbot/dns-route53
    container_name: certbot
    entrypoint: "certbot certonly -n --agree-tos --email pmanko@uw.edu -d '${DOMAIN}' -d '*.${DOMAIN}' --dns-route53 --preferred-challenges=dns"
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    volumes:
    - certs:/etc/letsencrypt
    - letsencrypt:/var/lib/letsencrypt
    networks:
    - sedish

  ###
  # OpenCR
  ###
  opencr:
    container_name: opencr
    hostname: opencr
    #image: intrahealth/opencr:latest
    image: intrahealth/opencr:fdb3d44
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
      - HAPI_FHIR_URL=http://opencr-fhir:8080/fhir/metadata
    networks:
      - sedish
    volumes:
      - ./configs/opencr/config_docker.json:/src/server/config/config_docker.json
      - ./configs/opencr/mediator.json:/src/server/config/mediator.json
      - ./configs/opencr/decisionRules.json:/src/server/config/decisionRules.json
      - /home/ubuntu/local/letsencrypt/live/isanteplus-pilot.org/privkey.pem:/src/server/serverCertificates/server_key.pem
      - /home/ubuntu/local/letsencrypt/live/isanteplus-pilot.org/fullchain.pem:/src/server/serverCertificates/server_cert.pem   
  
  opencr-fhir:
    image: hapiproject/hapi:latest
    container_name: opencr-fhir
    hostname: opencr-fhir
    restart: unless-stopped
    volumes:
      - cr-data:/data/hapi
    env_file:
      - configs/opencr-hapi/.env
    networks:
      - sedish
  
  opencr-es:
    container_name: es
    hostname: es
    image: intrahealth/elasticsearch:latest
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - sedish

  ###
  # SHR
  ###
  shr:
    container_name: shr
    hostname: shr
    image: ghcr.io/i-tech-uw/shared-health-record:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
    networks:
      - sedish
    volumes:
      - ./configs/shr/config_docker.json:/app/config/config_docker.json
      - ./configs/shr/mediator_docker.json:/app/config/mediator_docker.json
  
  shr-fhir:
    image: "hapiproject/hapi:latest"
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    volumes:
      - hapi-data:/data/hapi
    env_file:
      - ./configs/shr/.env
    networks:
      - sedish

  ###
  # iSantePlus
  ###
  isanteplus:
    container_name: isanteplus
    hostname: isanteplus
    image: ghcr.io/isanteplus/docker-isanteplus-server:latest
    restart: unless-stopped
    env_file:
        - ./configs/openmrs/openmrs-server.env
    volumes:
      - openmrs-data:/openmrs/data
    networks:
      - sedish

  isanteplus-two:
    container_name: isanteplus-two
    hostname: isanteplus-two
    image: ghcr.io/isanteplus/docker-isanteplus-server:latest
    restart: unless-stopped
    env_file:
        - ./configs/openmrs/openmrs-server-fsc.env
    volumes:
      - openmrs-data2:/openmrs/data
    networks:
      - sedish
    # ports:
    #     - 8001:8001
  ###
  # OpenHIM
  ###
  openhim-core:
    container_name: openhim-core
    hostname: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: mongodb://mongo:27017/openhim
      mongo_atnaUrl: mongodb://mongo:27017/openhim
      NODE_ENV: "production"
    ports:
      - 8080:8080
      - 5000:5000
      - 5001:5001
    healthcheck:
      test: "curl -sSk https://openhim-core:8080/heartbeat || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - sedish

  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    volumes:
      - ./configs/openhim-console/default.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - sedish

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
    networks:
      - sedish
    restart: unless-stopped

volumes:
  esdata:
    driver: local
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  openmrs-data:
    driver: local
  openmrs-data2:
    driver: local
  mongo-data:
    driver: local
  shr:
    driver: local
  cr-data:
    driver: local
  shr-data:
    driver: local
  data011:
    driver: local
  data012:
    driver: local
  es-data:
    driver: local    
  hapi-data:
    driver: local
  data011:
    driver: local
  data012:
    driver: local
  data013:
    driver: local    
  hapi-data:
    driver: local
  cr-data:
    driver: local
  certs:
    driver: local
  letsencrypt: 
    driver: local
  nginx-data: 
    driver: local
networks:
  sedish:
