version: "3.9"

services:
  postgresql-openxds:
    container_name: postgresql-openxds
    restart: always
    hostname: postgresql-openxds
    image: postgres:9.6-bullseye
 
    environment:
      - POSTGRES_USER=openxds
      - POSTGRES_PASSWORD=openxds
      - POSTGRES_DB=openxds
  
    networks:
      - openhim
    volumes:
      - xds-pg:/var/lib/postgresql/data
    configs:
      - target: /docker-entrypoint-initdb.d/initialize_db.sql
        source: initialize_db.sql
      - target: /docker-entrypoint-initdb.d/create_log2.sql
        source: create_log2.sql
      
configs:
  initialize_db.sql:
    file: ./config/initialize_db.sql
    name: openxds_initialize_db
    labels:
      name: openxds_initialize_db
  create_log2.sql:
    file: ./config/create_log2.sql
    name: openxds_create_log2
    labels:
      name: openxds_create_log2
volumes:
  xds-pg:

networks:
  openhim:
    external: true
    name: openhim_public





   
    

