version: '3.8'

services:
  lnsp-mediator:
    image: lnsp-mediator:local
    build: 
      context: ./
    container_name: lnsp-mediator
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    #restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

# docker run -it --rm --network host mongo mongosh --host localhost --port 27017 -u root -p example --authenticationDatabase admin
