version: "3.9"

services:
  isanteplus-mysql:
    image: ghcr.io/isanteplus/docker-isanteplus-db:vtestUpdatedDb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
    container_name: isanteplus-mysql
    environment:
      - MYSQL_DATABASE=${OMRS_MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${OMRS_MYSQL_ROOT_PW}
      - MYSQL_USER=${OMRS_CONFIG_CONNECTION_USERNAME}
      - MYSQL_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD}
      - MYSQL_ROOT_HOST=% # Allow docker containers to connect to mysql
    volumes:
      - "isanteplus-mysql-1-data:/var/lib/mysql"
    networks:
      - openhim
    configs:
      - source: mysql.cnf
        target: /etc/mysql/conf.d/custom.cnf

configs:
  mysql.cnf:
    file: ./config/mysql.cnf
    name: mysql.cnf
    labels:
      name: isanteplus

volumes:
  isanteplus-mysql-1-data:

networks:
  openhim:
    external: true
    name: openhim_public

