version: '3.9'

services:
  isanteplus:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_1}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_1}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_1}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus2:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_2}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_2}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_2}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus2-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus3:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_3}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_3}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_3}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus3-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus4:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_4}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_4}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_4}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus4-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus5:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_5}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_5}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_5}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus5-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus6:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_6}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_6}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_6}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus6-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus7:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_7}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_7}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_7}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus7-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus8:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_8}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_8}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_8}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus8-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus9:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_9}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_9}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_9}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus9-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

  isanteplus10:
    image: itechuw/docker-isanteplus-server:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OMRS_JAVA_MEMORY_OPTS=${OMRS_JAVA_MEMORY_OPTS}
      - OMRS_CONFIG_CONNECTION_SERVER=${OMRS_CONFIG_CONNECTION_SERVER}
      - OMRS_CONFIG_CREATE_DATABASE_USER=${OMRS_CONFIG_CREATE_DATABASE_USER}
      - OMRS_CONFIG_CREATE_TABLES=${OMRS_CONFIG_CREATE_TABLES}
      - OMRS_CONFIG_ADD_DEMO_DATA=${OMRS_CONFIG_ADD_DEMO_DATA}
      - OMRS_CONFIG_CONNECTION_URL=${OMRS_CONFIG_CONNECTION_URL_10}
      - OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE=${OMRS_CONFIG_HAS_CURRENT_OPENMRS_DATABASE}
      - OMRS_JAVA_SERVER_OPTS=${OMRS_JAVA_SERVER_OPTS}
      - OMRS_CONFIG_CONNECTION_USERNAME=${OMRS_CONFIG_CONNECTION_USERNAME_10}
      - OMRS_CONFIG_CONNECTION_PASSWORD=${OMRS_CONFIG_CONNECTION_PASSWORD_10}
      - OMRS_DEV_DEBUG_PORT=${OMRS_DEV_DEBUG_PORT}
    volumes:
      - isanteplus10-data:/openmrs/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - public
      - reverse-proxy
      - mysql

volumes:
  isanteplus-data:
  isanteplus2-data:
  isanteplus3-data:
  isanteplus4-data:
  isanteplus5-data:
  isanteplus6-data:
  isanteplus7-data:
  isanteplus8-data:
  isanteplus9-data:
  isanteplus10-data:
networks:
  public:
    external: true
    name: isanteplus_public
  mysql:
    external: true
    name: mysql_public
  reverse-proxy:
    name: reverse-proxy_public
    external: true
