version: "3.9"

services:
  mysql:
    ports:  
      - target: 3306
        published: 3336
        mode: host
    # Uncomment below to use local bind mount instead of Docker volume
    # volumes:
    #   - /home/ubuntu/db/mysql:/var/lib/mysql