version: "3.9"

services:
  mysql:
    image: ghcr.io/isanteplus/docker-isanteplus-db:vtestUpdatedDb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_USER=${MYSQL_CONNECTION_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_CONNECTION_PASSWORD}
      - MYSQL_ROOT_HOST=% # Allow docker containers to connect to mysql
    volumes:
      - "/var/lib/mysql"
    networks:
      - mysql
    configs:
      - source: mysql.cnf
        target: /etc/mysql/conf.d/custom.cnf
    ports:  
      - target: 3306
        published: 3336
        mode: host

configs:
  mysql.cnf:
    file: ./config/mysql.cnf
    name: mysql.cnf
    labels:
      name: mysql

networks:
  mysql:
    external: true
    name: mysql_public

