version: '3.9'

services:
  xds-mediator:
    container_name: xds-mediator
    hostname: xds-mediator
    image: itechuw/openhim-mediator-xds:v1.0.0
    restart: unless-stopped
    #image: ghcr.io/isanteplus/openhim-mediator-xds:local # Use with local build from ~/code/openhim-mediator-xds
   
    configs:
      - source: xds-config
        target: /mediator.properties
    
    networks:
      - openhim
    ports:
      - 1045:1044
      - 8500:8500
    entrypoint: 'java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 -jar /mediator-xds-1.1.0-SNAPSHOT-jar-with-dependencies.jar --conf /mediator.properties'

configs:
  xds-config:
    file: ./config/mediator.properties
    labels:
      name: xds

networks:
  openhim:
    name: openhim_public
    external: true
  default:
  




      

