version: "3.9"

services:
  openshr-db:
    container_name: openshr-db
    image: mysql:5.7
    command: --sql_mode="NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - OPENMRS_DATABASE=${OPENMRS_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}

    volumes:
      - "openshr-mysql-data1:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - openhim
volumes:
   openshr-mysql-data1:
networks:
  openhim:
    external: true
    name: openhim_public

