# docker run -it --rm --network host mongo mongosh --host localhost --port 27017 -u root -p example --authenticationDatabase admin

services:
  lnsp-mongo-1:
    image: mongo:latest
    restart: always
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - default
      - xds-repo-mongo

volumes:
  mongo-data:
    driver: local
networks:
  default:
  xds-repo-mongo:
    name: xds_repo_mongo
    external: true

# export MONGO_URL=mongodb://172.31.2.125:27019/nest

# docker run --rm -v "$(pwd)":/backup mongo:6.0 mongodump --uri "mongodb://172.31.2.125:27019/nest" --out /backup
# docker run --rm -v "$(pwd)/backup":/backup mongo:6.0 mongorestore --uri "mongodb://172.31.2.125:27019/nest" /backup/nest

