services:
  lnsp-mediator:
    ports:
      - target: 3000
        published: 3000
        mode: host
      - target: 9229
        published: 9229
        mode: host
    command: yarn start:debug
    environment:
      - NODE_ENV=development