# docker run -it --rm --network host mongo mongosh --host localhost --port 27017 -u root -p example --authenticationDatabase admin

services:
  mongo-1:
    image: ${MONGO_IMAGE}
    command: ["--replSet", "mongo-set", "--wiredTigerCacheSizeGB", "0.5"]
    volumes:
      - "openhim-mongo-01:/data/db"
      - "openhim-mongo-01-config:/data/configdb"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${MONGO_CPU_LIMIT}
          memory: ${MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENHIM_MONGO_CPU_RESERVE}
          memory: ${MONGO_MEMORY_RESERVE}
    networks:
      default:
      openhim-mongo:
      mongo_backup_net:

volumes:
  openhim-mongo-01:
  openhim-mongo-01-config:

networks:
  xds-repo-mongo:
    name: xds_repo_mongo
    external: true
  mongo_backup_net:
    name: mongo_backup
    driver: overlay
    attachable: true
  default: