services:
  lnsp-mediator:
    image: lnsp-mediator:local
    container_name: lnsp-mediator
    environment:
      - MONGO_URL=mongodb://lnsp-mongo-1:27017/nest
      - NODE_ENV=production
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    networks:
      - default
      - openhim
      - xds-repo-mongo

volumes:
  mongo-data:
    driver: local

networks:
  openhim:
    name: openhim_public
    external: true
  xds-repo-mongo:
    name: xds_repo_mongo
    external: true
  default:
  
# docker run -it --rm --network host mongo mongosh --host localhost --port 27017 -u root -p example --authenticationDatabase admin
