version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      environment:
      POSTGRES_MULTIPLE_DATABASES: opencr,shr
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data/
  
    configs:
      - target: /docker-entrypoint-initdb.d/multiple-db.sh
        source: multiple-db.sh
   
    networks:
      opencr:
      default:

configs:
  multiple-db.sh:
    file: ./config/postgres/multiple-db.sh
    name: multiple-db.sh
    labels:
      name: multiple-db.sh

networks:
  default:
  opencr:
    name: opencr
    external: true